
spring:
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
  datasource:
    url: jdbc:mariadb://localhost:33306/togaether?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, env, metrics, shutdown, info, health, beans
      base-path: /config

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    reactor:
      netty: DEBUG
#    io.bigin: DEBUG
#    io.bigin.cdp.auth.client: DEBUG

server:
  port: 8080

token:
  secret: 'a05*B2XlaS%Lr8t0SB*781SbEyQN3I%G'
  access:
    expiration_time: 3600
  refresh:
    expiration_time: 86400
  issuer: TOGAETHER
  audience: USER