# https://github.com/abagayev/docker-bootstrap-collection/tree/master/mysql-few-databases
version: '3.1'

volumes:
  db:
    driver: local
services:
  db:
    container_name: togaether-mariadb
    image: mariadb:10.4
    restart: always
    ports:
      - "33306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
