### 회원 가입
POST {{host}}:{{port}}/member
Content-Type: application/json

{
  "email": "jongsang@naver.com",
  "password": "abcd!23$",
  "name": "한종상",
  "birth": "1985-06-19"
}

### 회원 조회
GET {{host}}:{{port}}/member/jongsang@naver.com
Content-Type: application/json

### 내 프사 Upload
POST {{host}}:{{port}}
