### 회원 가입
POST {{host}}:{{port}}/member
Content-Type: application/json

{
  "email": "jongsang@naver.com",
  "password": "abcd!23$",
  "name": "한종상",
  "birth": "1985-06-19"
}

### 회원 조회
GET {{host}}:{{port}}/member/jongsang@naver.com
Content-Type: application/json

### 로그인
POST {{host}}:{{port}}/sign-in/member
Content-Type: application/json

{
  "email": "jongsang@naver.com",
  "password": "abcd!23$"
}

> {% //response handler
  client.global.set("token", response.body.data.jwt); // (1)
  client.log("token : " + client.global.get("token")); // (2)
%}


### 내 프사 Upload
POST {{host}}:{{port}}/member/upload-picture
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="profile"; filename="profile.png"
Content-Type: application/json

< profile.png

### 내 프로필 사진 조회
GET {{host}}:{{port}}/member/my-profile-picture
Content-Type: image/jpeg, image/png