### 회원 가입
POST {{host}}:{{port}}/member
Content-Type: application/json

{
  "email": "apitest@tagether.io",
  "password": "abcd1234",
  "name": "api-tester",
  "birth": "2023-01-15"
}

### 로그인
POST {{host}}:{{port}}/sign-in/member
Content-Type: application/json

{
  "email": "jongsang@togaether.io",
  "password": "abcd1234"
}

> {% //response handler
  client.global.set("token", response.body.jwt.access_token); // (1)
  client.log("token : " + client.global.get("token")); // (2)
%}

### 회원 조회
GET {{host}}:{{port}}/member/jongsang@tagether.io
Content-Type: application/json
Authorization: Bearer {{token}}




### 내 프사 Upload
POST {{host}}:{{port}}/member/upload-picture
Content-Type: multipart/form-data; boundary=boundary
Authorization: Bearer {{token}}

--boundary
Content-Disposition: form-data; name="profile_picture"; filename="profile.png"
Content-Type: application/json

< profile.png

### 내 프로필 사진 조회
GET {{host}}:{{port}}/member/my-profile-picture
Content-Type: image/jpeg, image/png
Authorization: Bearer {{token}}


### 나의 펫 조회
GET {{host}}:{{port}}/member/my-pets
Content-Type: application/json
Authorization: Bearer {{token}}

### 회원 탈퇴
POST {{host}}:{{port}}/member/withdraw
Content-Type: application/json
Authorization: Bearer {{token}}