### 펫 등록
POST {{host}}:{{port}}/pet
Content-Type: multipart/form-data; boundary=boundary;

--boundary
Content-Disposition: form-data; name="main_image"; filename="retriever.png";

< retriever.png

--boundary
Content-Disposition: form-data; name="pet_upload";
Content-Type: application/json

{
  "name": "뽀미",
  "species": "GORDON_SETTER",
  "pet_character": "FRIENDLY",
  "gender": "MALE",
  "birth": "2022-01-01",
  "description": "밝은 강아지",
  "etc": "한쪽눈이 불편해요."
}

### 펫 조회
GET {{host}}:{{port}}/pet/all
Content-Type: application/json

### 펫 메인 이미지 조회
GET {{host}}:{{port}}/pet/main-image/1
Content-Type: image/jpeg, image/png

### 펫 이미지 조회
GET {{host}}:{{port}}/pet/image
Content-Type: image/jpeg, image/png