package io.ddd.togaether.model;

import java.util.List;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * create on 2022/12/11. create by IntelliJ IDEA.
 *
 * <p> 클래스 설명 </p>
 * <p> {@link } and {@link }관련 클래스 </p>
 *
 * @author Jongsang Han(Henry)
 * @version 1.0
 * @see
 * @since 1.0
 */
@Getter
@RequiredArgsConstructor
public enum Species {
  GORDON_SETTER("고든 세터", "Gordon setter", "ㄱ"),
  COTON_DE_TULEAR("꼬똥 드 툴레아", "Coton de tulear","ㄱ"),
  GOLDEN_DOODLE("골든 두들", "Golden doodle","ㄱ"),
  GOLDEN_RETRIEVER("골든 리트리버", "Golden retriever","ㄱ"),
  GREAT_DANE("그레이트 데인", "Great dane","ㄱ"),
  GREATER_SWISS_MOUNTAIN_DOG("그레이트 스위스 마운틴 도그", "Greater swiss mountain dog","ㄱ"),
  GREAT_PYRENEES("그레이트 피레니즈", "Great pyrenees","ㄱ"),
  GREY_HOUND("그레이 하운드", "Grey hound","ㄱ"),
  GREENLAND_DOG("그린란드 견", "Greenland dog","ㄱ"),
  GLEN_OF_IMAAL_TERRIER("글렌 오브 이말 테리어", "Glen of imaal terrier","ㄱ"),
  KISHU_INU("기슈견", "Kishu inu","ㄱ"),
  NEOPOLITAN_MASTIFF("나폴리탄 마스티프", "Neopolitan mastiff","ㄴ"),
  NORWEGIAN_BUHUND("노르웨지안 부훈트", "Norwegian buhund","ㄴ"),
  NORWEGIAN_ELKHOUND("노르웨이 엘크 하운드", "Norwegian elkhound","ㄴ"),
  NORWICH_TERRIER("노리치 테리어", "Norwich terrier","ㄴ"),
  Nova_Scotia_Duck_Tolling_Retriever("노바 스코셔 덕 톨링 레트리버", "Nova scotia duck tolling retriever","ㄴ"),
  NEWFOUNDLAND("뉴펀들랜드", "Newfoundland","ㄴ"),
  DACHSHUND("닥스훈트", "Dachshund","ㄷ"),
  DALMATIAN("달마시안", "Dalmatian","ㄷ"),
  Dandie_dinmont_terrier("댄디 딘몬트 테리어", "Dandie dinmont terrier","ㄷ"),
  DOGO_CANARIO("도고 까나리오", "Dogo Canario","ㄷ"),
  Dogo_Argentino("도고 아르헨티노", "Dogo argentino","ㄷ"),
  DOGUE_DE_BORDEAUX("도그 드 보르도", "Dogue de bordeaux","ㄷ"),
  DOBERMAN_PINSCHER("도베르만 핀셔", "Doberman pinscher","ㄷ"),
  Tosa("도사견", "Tosa","ㄷ"),
  DONGGYEONG_DOG("동경이", "Donggyeong dog","ㄷ"),
  LAGOTTO_ROMAGNOLO("라고토 로마뇰로", "Lagotto romagnolo","ㄹ"),
  LHASA_APSO("라사압소", "Lhasa apso","ㄹ"),
  RAFEIRO_DO_ALENTEJO("라페이로 도 알렌테조", "Rafeiro do alentejo","ㄹ"),
  LAPPONIAN_HERDER("라포니안 허더", "Lapponian herder","ㄹ"),
  LABRADOR_RETRIEVER("래브라도 리트리버", "Labrador retriever","ㄹ"),
  LEONBERGER("레온베르거", "Leonberger","ㄹ"),
  LAKELAND_TERRIER("레이크랜드 테리어", "Lakeland terrier","ㄹ"),
  RHODESIAN_RIDGEBACK("로디지아 리지백", "Rhodesian ridgeback","ㄹ"),
  LOWCHEN("로첸", "Lowchen","ㄹ"),
  ROTTWEILER("로트와일러", "Rottweiler","ㄹ"),
  MASTIFF("마스티프", "Mastiff","ㅁ"),
  MANCHESTER_TERRIER("맨체스터 테리어", "Manchester terrier","ㅁ"),
  MALTESE("말티즈", "Maltese","ㅁ"),
  MINIATURE_BULL_TERRIER("미니어처 불 테리어", "Miniature bull terrier","ㅁ"),
  MINIATURE_SCHNAUZER("미니어처 슈나우저", "Miniature schnauzer","ㅁ"),
  MINIATURE_PINSCHER("미니어처 핀셔", "Miniature pinscher","ㅁ"),
  MALTIPOO("말티푸", "Maltipoo","ㅁ"),
  BASENJI("바센지", "Basenji","ㅂ"),
  BASSET_HOUND("바셋 하운드", "Basset hound","ㅂ"),
  BERNESE_MOUNTAIN_DOG("버니즈 마운틴 도그", "Bernese mountain dog","ㅂ"),
  BEDLINGTON_TERRIER("베들링턴 테리어", "Bedlington terrier","ㅂ"),
  BALBARI("발바리", "Balbari","ㅂ"),
  BELGIAN_MALINOIS("벨기에 말리노이즈", "Belgian malinois","ㅂ"),
  BELGIAN_TERVUREN("벨기에 테뷰런", "Belgian tervuren","ㅂ"),
  BELGIAN_GRIFFON("벨지안 그리펀", "Belgian griffon","ㅂ"),
  BELGIAN_SHEEPDOG("벨지언 쉽독", "Belgian sheepdog","ㅂ"),
  BORDER_COLLIE("보더 콜리", "Border collie","ㅂ"),
  BORDER_TERRIER("보더 테리어", "Border terrier","ㅂ"),
  BORDEAUX_MASTIFF("보르도 마스티프", "Bordeaux mastiff","ㅂ"),
  BORZOI("보르조이", "Borzoi","ㅂ"),
  BOUVIER_DES_FLANDRES("보비에 드 플랜더스", "Bouvier des flandres","ㅂ"),
  BEAUCERON("보스롱", "Beauceron","ㅂ"),
  BOSTON_TERRIER("보스턴 테리어", "Boston terrier","ㅂ"),
  BOXER("복서", "boxer","ㅂ"),
  BOLOGNESE("볼로네즈", "Bolognese","ㅂ"),
  BULGAE("불개", "Bulgae","ㅂ"),
  BULLDOG("불도그", "Bulldog","ㅂ"),
  BULLY_KUTTA("불리 쿠타", "Bully kutta","ㅂ"),
  BULL_MASTIFF("불 마스티프", "Bull mastiff","ㅂ"),
  BULL_TERRIER("불 테리어", "Bull terrier","ㅂ"),
  BRUSSELS_GRIFFON("브뤼셀 그리펀", "Brussels griffon","ㅂ"),
  BRIARD("브리어드", "Briard","ㅂ"),
  BRITTANY("브리타니", "Brittany","ㅂ"),
  BLACK_RUSSIAN_TERRIER("블랙 러시안 테리어", "Black russian terrier","ㅂ"),
  BLACK_AND_TAN_COONHOUND("블랙 앤드 탄 쿤하운드", "Black and tan coonhound","ㅂ"),
  BLOOD_HOUND("블러드 하운드", "Blood hound","ㅂ"),
  BEAGLE("비글", "beagle","ㅂ"),
  BICHON_FRISE("비숑 프리제", "Bichon frise","ㅂ"),
  BEARDED_COLLIE("비어디드 콜리", "Bearded collie","ㅂ"),
  VIZSLA("비즐라", "Vizsla","ㅂ"),
  PAPILLON("빠삐용", "papillon","ㅂ"),
  SAMOYED_DOG("사모예드", "Samoyed dog","ㅅ"),
  SARPLANINAC("사플라니낙", "Sarplaninac","ㅅ"),
  SALUKI("살루키", "Saluki","ㅅ"),
  SAPSAL_DOG("삽살개", "sapsal dog","ㅅ"),
  SHAR_PEI("샤페이", "Shar pei","ㅅ"),
  SUSSEX_SPANIEL("서식스 스패니얼", "Sussex spaniel","ㅅ"),
  SAINT_BERNARD("세인트 버나드", "Saint bernard","ㅅ"),
  SHETLAND_SHEEPDOG("셰틀랜드 쉽독", "Shetland sheepdog","ㅅ"),
  SOFT_COATED_WHEATEN_TERRIER("소프트 코티드 휘튼 테리어", "Soft coated wheaten terrier","ㅅ"),
  XOLOITZ_CUINTLE("솔로이츠 쿠인틀레", "xoloitz cuintle","ㅅ"),
  SMOOTH_FOX_TERRIER("스무드 폭스 테리어", "Smooth fox terrier","ㅅ"),
  SWEDISH_VALLHUND("스웨디쉬 발훈트", "Swedish vallhund","ㅅ"),
  SKYE_TERRIER("스카이 테리어", "Skye terrier","ㅅ"),
  SCOTTISH_DEERHOUND("스코티시 디어하운드", "Scottish deerhound","ㅅ"),
  SCOTTISH_TERRIER("스코티시 테리어", "Scottish terrier","ㅅ"),
  SCHIPPERKE("스키퍼키", "Schipperke","ㅅ"),
  STAFFORDSHIRE_BULL_TERRIER("스태퍼드셔 불 테리어", "Staffordshire bull terrier","ㅅ"),
  STANDARD_SCHNAUZER("스탠더드 슈나우저", "Standard schnauzer","ㅅ"),
  SPANISH_GREYHOUND("스패니쉬 그레이 하운드", "Spanish greyhound","ㅅ"),
  SPANISH_MASTIFF("스패니쉬 마스티프", "Spanish mastiff","ㅅ"),
  SPINONE_ITALIANO("스피노네 이탈리아노", "Spinone italiano","ㅅ"),
  SPITZ("스피츠", "Spitz","ㅅ"),
  SIGOREUJABEUJONG("시고르자브종", "Sigoreujabeujong","ㅅ"),
  SHIBA_INU("시바 이누", "Shiba inu","ㅅ"),
  SIBERIAN_HUSKY("시베리언 허스키", "Siberian husky","ㅅ"),
  CHICHU("시추", "Chichu","ㅅ"),
  SHIKOKU_KEN("시코쿠견", "Shikoku ken","ㅅ"),
  SEALYHAM_TERRIER("실리엄 테리어", "Sealyham terrier","ㅅ"),
  SILKY_TERRIER("실키 테리어", "Silky terrier","ㅅ"),
  ANATOLIAN_SHEPHERD("아나톨리아 셰퍼드", "Anatolian shepherd","ㅇ"),
  AMERICAN_BULLDOG("아메리칸 불도그", "American bulldog","ㅇ"),
  AMERICAN_BULLY("아메리칸 불리", "American bully","ㅇ"),
  AMERICAN_STAFFORDSHIRE_TERRIER("아메리칸 스태퍼드셔 테리어", "American staffordshire terrier","ㅇ"),
  AMERICAN_AKITA("아메리칸 아키다", "American akita","ㅇ"),
  AMERICAN_ESKIMO_DOG("아메리칸 에스키모 도그", "American eskimo dog","ㅇ"),
  AMERICAN_WATER_SPANIEL("아메리칸 워터 스패니얼", "American water spaniel","ㅇ"),
  AMERICAN_COCKER_SPANIEL("아메리칸 코커 스패니얼", "American cocker spaniel","ㅇ"),
  AMERICAN_FOXHOUND("아메리칸 폭스하운드", "American foxhound","ㅇ"),
  AIDI("아이디", "Aidi","ㅇ"),
  IRISH_SOFT_COATED_WHEATEN_TERRIER("아이리시 소프트코티드 휘튼 테리어", "Irish soft coated wheaten terrier","ㅇ"),
  IRISH_RED_AND_WHITE_SETTER("아이리시 레드 앤드 화이트 세터", "Irish red and white setter","ㅇ"),
  IRISH_SETTER("아이리시 세터", "Irish setter","ㅇ"),
  IRISH_WOLF_HOUND("아이리시 울프 하운드", "Irish wolf hound","ㅇ"),
  IRISH_WATER_SPANIEL("아이리시 워터 스패니얼", "Irish water spaniel","ㅇ"),
  IRISH_TERRIER("아이리시 테리어", "Irish terrier","ㅇ"),
  AKITA_INU("아키타 이누", "Akita inu","ㅇ"),
  AFFENPINSCHER("아펜핀셔", "Affenpinscher","ㅇ"),
  AFGHAN_HOUND("아프간 하운드", "Afghan hound","ㅇ"),
  ALASKAN_MALAMUTE("알래스칸 맬러뮤트", "Alaskan malamute","ㅇ"),
  ALASKAN_KLEE_KAI("알래스칸 클리 카이", "Alaskan klee kai","ㅇ"),
  ESTRELA_MOUNTAIN_DOG("에스트렐라 마운틴 독", "Estrela mountain dog","ㅇ"),
  AIREDALE_TERRIER("에어데일 테리어", "Airedale terrier","ㅇ"),
  OVCHARKA("오브차카", "Ovcharka","ㅇ"),
  AUSTRALIAN_SILKY_TERRIER("오스트레일리안 실키 테리어", "Australian silky terrier","ㅇ"),
  AUSTRALIAN_KELPIE("오스트레일리안 켈피", "Australian Kelpie","ㅇ"),
  AUSTRALIAN_SHEPHERD("오스트레일리언 셰퍼드", "Australian shepherd","ㅇ"),
  AUSTRALIAN_CATTLE_DOG("오스트레일리언 캐틀 도그", "Australian cattle dog","ㅇ"),
  AUSTRALIAN_TERRIER("오스트레일리언 테리어", "Australian terrier","ㅇ"),
  OTTER_HOUND("오터 하운드", "Otter hound","ㅇ"),
  OLD_ENGLISH_SHEEPDOG("올드 잉글리시 쉽독", "Old english sheepdog","ㅇ"),
  WEIMARANER("와이머라너", "Weimaraner","ㅇ"),
  WIRE_FOX_TERRIER("와이어 폭스 테리어", "Wire fox terrier","ㅇ"),
  WIREHAIRED_POINTING_GRIFFON("와이어헤어드 포인팅 그리펀", "Wirehaired pointing griffon","ㅇ"),
  YAKUTIAN_LAIKA("야쿠탄 라이카", "Yakutian laika","ㅇ"),
  YORKSHIRE_TERRIER("요크셔 테리어", "Yorkshire terrier","ㅇ"),
  WEST_HIGHLAND_WHITE_TERRIER("웨스트 하이랜드 화이트테리어", "West highland white terrier","ㅇ"),
  WELSH_SPRINGER_SPANIEL("웰시 스프링어 스패니얼", "Welsh springer spaniel","ㅇ"),
  WELSH_CORGI("웰시 코기", "Welsh corgi","ㅇ"),
  WELSH_TERRIER("웰시 테리어", "Welsh terrier","ㅇ"),
  IBIZAN_HOUND("이비전 하운드", "Ibizan hound","ㅇ"),
  ITALIAN_GREYHOUND("이탤리언 그레이하운드", "Italian greyhound","ㅇ"),
  ENGLISH_SETTER("잉글리시 세터", "English setter","ㅇ"),
  ENGLISH_SPRINGER_SPANIEL("잉글리시 스프링어 스패니얼", "English springer spaniel","ㅇ"),
  ENGLISH_COCKER_SPANIEL("잉글리시 코커 스패니얼", "English Cocker Spaniel","ㅇ"),
  ENGLISH_TOY_SPANIEL("잉글리시 토이 스패니얼", "English toy spaniel","ㅇ"),
  ENGLISH_FOXHOUND("잉글리시 폭스하운드", "English foxhound","ㅇ"),
  GIANT_SCHNAUZER("자이언트 슈나우저", "Giant schnauzer","ㅈ"),
  JAPANESE_CHIN("재패니즈 친", "Japanese chin","ㅈ"),
  JAPANESE_SPITZ("재패니즈 스피츠", "Japanese spitz","ㅈ"),
  JACK_RUSSELL_TERRIER("잭 러셀 테리어", "Jack russell terrier","ㅈ"),
  GERMAN_SHEPHERD("저먼 셰퍼드", "German shepherd","ㅈ"),
  GERMAN_SHORTHAIRED_POINTER("저먼 쇼트헤어드 포인터", "German shorthaired pointer","ㅈ"),
  GERMAN_WIREHAIRED_POINTER("저먼 와이어헤어드 포인터", "German wirehaired pointer","ㅈ"),
  GERMAN_PINSCHER("저먼 핀셔", "German pinscher","ㅈ"),
  GERMAN_HUNTING_TERRIER("저먼 헌팅 테리어", "German hunting terrier","ㅈ"),
  JEJU_DOG("제주개", "Jeju dog","ㅈ"),
  JINDO_DOG("진돗개", "Jindo dog","ㅈ"),
  CHOW_CHOW("차우차우", "Chow chow","ㅊ"),
  CHINESE_SHARES_PEI("차이니즈 샤페이", "Chinese shares pei","ㅊ"),
  CHINESE_CRESTED_DOG("차이니즈 크레스티드", "Chinese crested dog","ㅊ"),
  CHESAPEAKE_BAY_RETRIEVER("체서피크 베이 레트리버", "Chesapeake bay retriever","ㅊ"),
  CZECHOSLOVAKIAN_WOLFDOG("체코슬로바키아 늑대개", "Czechoslovakian wolfdog","ㅊ"),
  CHIHUAHUA("치와와", "Chihuahua","ㅊ"),
  CANE_CORSO("카네 코르소", "Cane corso","ㅋ"),
  CARDIGAN_WELSH_CORGI("카디건 웰시 코기", "Cardigan welsh corgi","ㅋ"),
  CAVALIER_KING_CHARLES_SPANIEL("카발리에 킹 찰스 스파니엘", "Cavalier king charles spaniel","ㅋ"),
  KANGAL("캉갈", "Kangal","ㅋ"),
  CURLY_COATED_RETRIEVER("컬리 코티드 레트리버", "Curly coated retriever","ㅋ"),
  KERRY_BLUE_TERRIER("케리 블루 테리어", "Kerry blue terrier","ㅋ"),
  CAIRN_TERRIER("케언 테리어", "Cairn terrier","ㅋ"),
  CANAAN_DOG("케이넌 도그", "Canaan dog","ㅋ"),
  KEESHOND("케이스혼트", "Keeshond","ㅋ"),
  KOREAN_MASTIFF("코리안 마스티프", "Korean mastiff","ㅋ"),
  KOMONDOR("코몬도르", "Komondor","ㅋ"),
  COCKER_SPANIEL("코커 스패니얼", "Cocker spaniel","ㅋ"),
  COLLIE("콜리", "Collie","ㅋ"),
  KUVASZ("쿠바스", "Kuvasz","ㅋ"),
  KOOIKERHONDJE("쿠이커혼제", "Kooikerhondje","ㅋ"),
  CLUMBER_SPANIEL("클럼버 스패니얼", "Clumber spaniel","ㅋ"),
  TOY_FOX_TERRIER("토이 폭스 테리어", "Toy fox terrier","ㅋ"),
  TIBETAN_MASTIFF("티베탄 마스티프", "Tibetan mastiff","ㅋ"),
  TIBETAN_SPANIEL("티베탄 스패니얼", "Tibetan spaniel","ㅋ"),
  TIBETAN_TERRIER("티베탄 테리어", "Tibetan terrier","ㅋ"),
  PHARAOH_HOUND("파라오 하운드", "Pharaoh hound","ㅍ"),
  PARSON_RUSSELL_TERRIER("파슨 러셀 테리어", "Parson russell terrier","ㅍ"),
  PATTERDALE_TERRIER("패터데일 테리어", "Patterdale terrier","ㅍ"),
  PUG("퍼그", "Pug","ㅍ"),
  PEKINGESE("페키니즈", "Pekingese","ㅍ"),
  PEMBROKE_WELSH_CORGI("펨브록 웰시 코기", "Pembroke welsh corgi","ㅍ"),
  PORTUGUESE_WATER_DOG("포르투기즈 워터 도그", "Portuguese water dog","ㅍ"),
  POMERANIAN("포메라니안", "Pomeranian","ㅍ"),
  POINTER("포인터", "Pointer","ㅍ"),
  FOX_TERRIER("폭스 테리어", "Fox terrier","ㅍ"),
  POLISH_LOWLAND_SHEEPDOG("폴리시 롤런드 시프도그", "Polish lowland sheepdog","ㅍ"),
  POMPITZ("폼피츠", "pompitz","ㅍ"),
  PUDDLE("푸들", "Puddle","ㅍ"),
  PUMI("푸미", "Pumi","ㅍ"),
  PULI_DOG("풀리", "Puli dog","ㅍ"),
  POONGSAN_DOG("풍산개", "Poongsan dog","ㅍ"),
  FRENCH_BULLDOG("프렌치 불도그", "French bulldog","ㅍ"),
  PETIT_BASSET_GRIFFON_VENDEEN("프티 바세 그리퐁 방댕", "Petit basset griffon vendeen","ㅍ"),
  FLAT_COATED_RETRIEVER("플랫 코티드 레트리버", "Flat coated retriever","ㅍ"),
  PLOTT_HOUND("플롯 하운드", "Plott hound","ㅍ"),
  FINNISH_SPITZ("피니시 스피츠", "Finnish spitz","ㅍ"),
  PYRENEAN_MASTIFF("피레니안 마스티프", "Pyrenean mastiff","ㅍ"),
  PYRENEAN_SHEEPDOG("피레니안 쉽독", "Pyrenean sheepdog","ㅍ"),
  PYRENEAN_SHEPHERD("피레니언 셰퍼드", "Pyrenean shepherd","ㅍ"),
  FIELD_SPANIEL("필드 스패니얼", "Field spaniel","ㅍ"),
  FILA_BRASILEIRO("필라 브라질레이로", "Fila brasileiro","ㅍ"),
  PIT_BULL_TERRIER("핏 불 테리어", "Pit bull tERRIER","ㅍ"),
  HARRIER("해리어", "Harrier","ㅎ"),
  HAVANESE("하바니즈", "Havanese","ㅎ"),
  HOKKAIDO_INU("홋카이도 이누", "Hokkaido inu","ㅎ"),
  WHIPPET("휘핏", "Whippet","ㅎ"),

  ;


  private final String korName;
  private final String engName;
  private final String indexCode;

  public static List<Species> getAll() {
    return List.of(Species.values());
  }

}
